version: "3.0"

services:
    jenslaufer-site:
      image: jekyll/jekyll:3.8.5
      container_name: jenslaufer-site
      volumes:
        - .:/srv/jekyll
      ports:
        - 8080:4000
      entrypoint: jekyll serve --trace #-H localhost
