---
title: "Training a Neural Network in Docker"
subtitle: "Case study of training a shallow neural network on top of a InterceptionV3 model on CIFAR-10 within Docker on AWS"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In my last article about [Example Use Cases of Docker in the Data Science Process](https://jenslaufer.com/data/science/use-cases-of-docker-in-the-data-science-process.html)  I was talking more in general about Docker in Data Science. This time I want to get my hands dirty with a more practical example.

In this case study I want to show you how to train a shallow neural network on top of a InterceptionV3 model on CIFAR-10 within a Docker container. I want to use Keras with Tensorflow. Before going into the details I want to define some requirements for this little project:

- Training should be done on AWS (or Azure, GCloud, Alibaba Cloud) on a GPU empowered instance 
- NVIDIA docker is used to be able to train with GPU power
- The whole data pipeline is covered within the container
- The different models are persisted with all models meta data on MongoDB
- Usage of Docker compose, as we have a multi container application (training container + MongoDB)

Input: 
The docker container is parameterized from outsite with a JSON file with all parameters for each training session:

- session name 
- optimizer
- learning rate
- batch size
- number of epochs

Output:

Within 

- hdf5 model file
- model accuracy
- training parameters (session name, optimizer)




