---
title: "The little secret that let's your data science code shine"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,
                      message = F,
                      warning = F)
```

Lately I had to develop a predictive model for a client. We all know how it is, you are under pressure to get the things right fast. You craft some Jupyter notebooks to explore the data and to clean it. You build models, go back and forward, move from one to another Notebook and copy code. Sooner or later you end up in a mess. But while I am not so experienced with data science, I have 20 years of experience in software engineering in Java. I felt embarrassed with my working style, because from the perspectitive of my inner software engineer that working style is completely unacceptable. My only excuse was the pressure I was faced to. 

I gave me day to review my code and clean it. There were some mistakes I made. Copy and pasting code is one of the worst practices you can think of. Another mistake was that I was misusing Jupyter Notebooks as an IDE instead what they are actually brilliant for: Taking and presenting notes along with code that is needed to do stuff. Code in Notebooks is difficult to maintain and is not traceable as it does not integrate well into version control systems like Git. I ended up reducing the code in the notebooks to the bare minimum. This made the notebooks clearer. Now I could take the advantages of version controlling of the code with Git and could use use my favorite editor. 

There was that one little secret we all know that helped me out and let my code shine again and being completely flexible again:

__M O D U L E S__


## 1. What is a Python module?

A module is a Python object with arbitrarily named attributes that you can bind and reference. Simply, a module is a file consisting of Python code.

It's easy Python basics. I quickly demonstrate the usage of a module along with a Jupyter Notebook. Moving functionality to a module is simple: Put the code into functions and move this function to new Python file. The advantage of this that you can reduce the code in the notebook. Choose the function names wisely which makes the code fragments self-explaining without the need of extra comments. 


Jupyter have problem to reload the changes from modules. Add the following lines on top of your notebook to activate the auto-reload of module.

```python
%load_ext autoreload
%autoreload 2
```


## 2. What is a package in Python?

Packages allow for a hierarchical structuring of the module namespace using dot notation. In the same way that modules help avoid collisions between global variable names, packages help avoid collisions between module names. Creating a package is quite straightforward, since it makes use of the operating system’s inherent hierarchical file structure. 



## 3. How to create a Python package in Git and install it from there


The real power come when you put your packages under version control in Git e.g on

## 4. Advantages

p

- Easier to ship your code with Docker
- Easier to move from local coding to Colab
- Code can be unit tested
